[system]
backend_uri = "duckdb://md:birdbrain"

[docs]
backend_uri = "duckdb://md:birdbrain_docs"

[data]
backend_uris = [
    "duckdb://md:tpch",
    "duckdb://md:imdb",
    "duckdb://md:ibis_analytics",
]
