[data]
# birdbrain
memory = "duckdb://md:"
system = "duckdb://md:birdbrain"
documentation = "duckdb://md:birdbrain_docs"

# demos
#tpch = "duckdb://md:tpch"
#imdb = "duckdb://md:imdb"
penguins = "duckdb://md:penguins"

# actual prod data
#ibis_adoption_metrics = "duckdb://md:ibis_analytics"
