# Why Ibis Birdbrain?

[Ibis](https://ibis-project.org) is the portable Python dataframe library.

Ibis Birdbrain is the portable Python AI-powered data bot, powered by Ibis and thus supporting all data platforms Ibis supports. Birdbrain is also built on [Marvin](https://github.com/PrefectHQ/marvin), thus supporting all AI platform providers Marvin supports. While this list is currently low, we expect to support a wide breadth of data and AI platforms in Ibis Birdbrain.

## Standards

> > When things don't work as they should, it often means that standards are absent.
> >
> > \- [The International Organization for Standardization (ISO)](https://www.iso.org/standards.html)
> 
> \- [The Composable Codex](https://voltrondata.com/codex/standards-over-silos)

## Composable data systems are MICE

[Composable data systems are MICE: modular, interoperable, customizable, and extensible](https://voltrondata.com/codex/standards-over-silos). Ibis Birdbrain aims to bring these values to a data + AI framework that makes working with LLMs delightful and easy, for individual hobbiests or the more advanced technology organizations.

